[versions]
loom = "1.17-SNAPSHOT"
kotlin = "2.4.10"

devauth = "1.2.2"
kommand = "1.0.2"

fabric-loader = "0.19.3"
fabric-language-kotlin = "1.13.13+kotlin.2.4.10"

fabric-api-26-1 = "0.155.2+26.1.2"
fabric-api-26-2 = "0.158.0+26.2"

snowbird-26-1 = "016+26.1"
snowbird-26-2 = "016+26.2"

bytebuddy = "1.15.11"

[libraries]
bytebuddy-agent = { module = "net.bytebuddy:byte-buddy-agent", version.ref = "bytebuddy" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
kommand = { module = "foo.starred:kommand", version.ref = "kommand" }

fabric-api-26-1 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api-26-1" }
fabric-api-26-2 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api-26-2" }

snowbird-26-1 = { module = "foo.starred:snowbird", version.ref = "snowbird-26-1" }
snowbird-26-2 = { module = "foo.starred:snowbird", version.ref = "snowbird-26-2" }

kscript-common = { module = "org.jetbrains.kotlin:kotlin-scripting-common", version.ref = "kotlin" }
kscript-host = { module = "org.jetbrains.kotlin:kotlin-scripting-jvm-host", version.ref = "kotlin" }
kscript-jvm = { module = "org.jetbrains.kotlin:kotlin-scripting-jvm", version.ref = "kotlin" }
kscript-runtime = { module = "org.jetbrains.kotlin:kotlin-script-runtime", version.ref = "kotlin" }
kscript-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable", version.ref = "kotlin" }
kscript-compiler-impl-embeddable = { module = "org.jetbrains.kotlin:kotlin-scripting-compiler-impl-embeddable", version.ref = "kotlin" }
kdaemon-embeddable = { module = "org.jetbrains.kotlin:kotlin-daemon-embeddable", version.ref = "kotlin" }

[bundles]
kotlin-extra = [
    "kscript-common",
    "kscript-host",
    "kscript-jvm",
    "kscript-runtime",
    "kscript-compiler-embeddable",
    "kscript-compiler-impl-embeddable",
    "kdaemon-embeddable"
]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
loom-obf = { id = "fabric-loom", version.ref = "loom" }
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
